###send post todos
POST http://localhost:8080/api/add-todo
content-type: application/json

{
  "title":"ini pertama buat api pake TypeScript",
  "status":"success"
}

###getData
GET http://localhost:8080/api/getTodos
content-type: application/json

{

}